---
title: "gghdr: Graphing highest density regions using grammar of graphics"
author: "Sayani Gupta <hr> Department of Econometrics and Business Statistics, Monash University"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```


The `gghdr` package provides the framework to visualize Highest Density Regions (HDR) with the grammar of graphics as implemented by `ggplot2`. There are several statistical methods to summarize a distribution by region of the sample space covering certain probability. For example, in a traditional boxplot, the central box bounded by the interquartile range represents 50% coverage and whiskers represents 99% coverage for large samples. The method of summarizing a distribution using highest density regions are useful for plotting multimodal distributions. Highest density regions might include several disjoint subsets each covering a local mode. This work extends the functionality of `ggplot2` by making a combination of calls to new `stat_*` and `geom_*` functions. The `stat_*` functions are inherited from the R package `hdrcde` and new `geom_*` functions are created to produce the new plotting framework. It enhances users' ability to customise and combine highest density regions (using box plots, scatterplots and rug plots) with other statistical distribution plots available under ggplot2 framework to highlight different features of a distribution. 


Other authors of the `gghdr` package are Mitchell O'Hara-Wild (Monash University), Stephen Pearce (CSIRO), Ryo Nakagawara (ACDI/VOCA), Darya Vanichkina (University of Sydney), Emi Tanaka (Monash University) and Thomas Fung (Macquarie University).

1) Hyndman, Rob J. 1996. “Computing and Graphing Highest Density Regions.” The American Statistician 50 (2): 120–26.

2) Hyndman RJ (2018). _hdrcde: Highest Density Regions and
Conditional Density Estimation_. R package version 3.3,
<URL: http://pkg.robjhyndman.com/hdrcde>.

